```{r}
library(pacman)
p_load(data.table, dplyr, ggplot2, stringr, foreach, scales, ggpubr, RColorBrewer, 
      ComplexHeatmap, tximport, DT, Glimma, EnrichmentBrowser, scatterplot3d, clusterProfiler, ggpmisc, pathview, readr, DEFormats,
      readr, DESeq2, patchwork)
options(scipen=999)
knitr::opts_chunk$set(fig.width=9, fig.height=5)
FC <- 2
lfc <- log2(FC)
pval <- 0.05
gff <- rtracklayer::import("NC_009004_with_sRNA.gff")
mcols(gff) <- mcols(gff)[, c("ID", "Name", "gene", "gene_biotype", "locus_tag", "old_locus_tag", "Ontology_term", "product")]
geneTable <- gff[!is.na(mcols(gff)$gene_biotype)] %>% 
  as.data.table() %>% 
  .[, .(ID, Name, gene, gene_biotype, locus_tag, old_locus_tag)]

geneTable <- merge(geneTable, gff[is.na(mcols(gff)$gene_biotype)] %>% .[, c("locus_tag", "product")] %>% as.data.table() %>% .[, c("locus_tag", "product")] %>% unique)
dir.create(outdatadir, recursive=TRUE)
```

```{r}
getCorHeatmap <- function(x) {
  d <- cor(log2(x+1))
  fig <- Heatmap(d, name="correlation", column_title = "Correlation", 
    heatmap_legend_param = list(direction = "horizontal"),
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.3f", d[i, j]), x, y, gp = gpar(fontsize = 10))
                                                         },
    column_title_gp = gpar(fontsize = 20, fontface = "bold"))
  return(fig)
}

makePCA <- function(x, title="PCA on vst transformed counts") {
  pcaData <- plotPCA(x, intgroup=c("group", "replicate"), returnData=TRUE)
  percentVar <- round(100 * attr(pcaData, "percentVar"))
  pcaData %>%
    as.data.table() %>% 
    .[, replicate := as.character(replicate)] %>% 
    ggplot(aes(PC1, PC2, color=group.1, shape=replicate)) +
      geom_point(size=3) +
      xlab(paste0("PC1: ",percentVar[1],"% variance")) +
      ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
      coord_fixed() +
      theme_bw() +
      ggtitle(title) +
      scale_color_brewer(palette="Dark2") +
      labs(color = "Sample") + 
      theme(legend.position="bottom")
}

getHeatMapDEG <- function(x, significant) {
  tmp <- x[significant$rn,] 
  d <- tmp %>% 
    t() %>%
    scale() %>%
    t() 
  rownames(d) <- rownames(tmp)
  gb <- grid.grabExpr(draw(Heatmap(d, name="Z-score", column_title = "Selected genes", column_dend_reorder=FALSE)))
  return(gb)
}

getVolcano <- function(x, pval, lfc, titlas="Simple Volcano plot") {
  as.data.frame(x) %>%
    as.data.table(., keep.rownames=FALSE) %>% 
    .[!is.na(padj), ] %>% 
    .[!is.na(log2FoldChange), ] %>% 
    .[, statistika := "Non significant"] %>% 
    .[(padj <= pval) , statistika := "pvalue"] %>% 
    .[(abs(log2FoldChange) >= lfc), statistika := "LFC"] %>% 
    .[(padj <= pval) & (abs(log2FoldChange) >= lfc), statistika := "LFC and pvalue"] %>% 
    .[, type := "protein"] %>% 
    .[, ykras := -log10(padj)]  %>% 
    .[!is.na(ykras), ] %>% 
    ggplot(aes(log2FoldChange, ykras, color=statistika, shape=type), size=2) +
      geom_point(size=2) +
      theme_bw() +
      xlab("Log 2 Fold change") +
      ylab("-log10 (padj)") +
      ggtitle(titlas) +
      theme(legend.position="bottom") +
      scale_color_manual(values = c(brewer.pal(9, "Greens")[5], brewer.pal(9, "Reds")[5],  "grey", brewer.pal(9, "Blues")[5]), guide = guide_legend(override.aes = list(size = 2))) +
      guides(color=guide_legend(nrow=2,byrow=TRUE), 
            shape=guide_legend(nrow=2,byrow=TRUE))
}
```

```{r}
samplesInfo <- expand.grid(c("Control", "Sample"), c("R1", "R2", "R3")) %>% 
  as.data.table() %>% 
  .[, Barcode := paste0(Var1, "_", Var2)] %>% 
  .[, name := Barcode] %>% 
  .[, replicate := str_extract(name, "R.")] %>% 
  .[, group := gsub("_R.", "", name)]
samples2do <- samplesInfo[, Barcode]
# Path to stringtie results 
files <- paste0("2024_MAPS/output/", samples2do, "/NotDedup/t_data.ctab")

tmp <- read_tsv(files[1])
tx2txt <- tmp[, c("t_name", "t_name")] %>% setnames(., c("t_name", "gene_name"))
tx2txt$gene_name <- gsub("gene-", "", tx2txt$gene_name) %>% gsub("rna-", "", .) %>% gsub("sRNR_", "", .)
tx2gene <- tmp[, c("t_name", "gene_name")] 
txi <- tximport(files, type = "stringtie", tx2gene = tx2txt)
## Removing Ribosomes genes 
ribo_ID <- geneTable[(gene_biotype %in% c("tRNA", "rRNA")), locus_tag]
i <- (rownames(txi[[1]]) %in% ribo_ID)

txi[[1]] <- txi[[1]][!i, ]
txi[[2]] <- txi[[2]][!i, ]
txi[[3]] <- txi[[3]][!i, ]

colnames(txi$counts) <- samplesInfo$Barcode
samplesInfo$group <- factor(samplesInfo$group, levels=c("Control", "Sample"))
dds <- DESeqDataSetFromTximport(txi, samplesInfo, ~group)
dds <- DESeq(dds)
saveRDS(dds, paste0(outdatadir, "dds_simpleModel.RDS"))
res <- results(dds)
res_dt <- as.data.frame(res) %>% 
  as.data.table(., keep.rownames=TRUE)
toSave <- merge(res_dt[order(-padj)] %>% .[, seq := NULL], geneTable, by.x="rn", by.y="locus_tag", all.x=TRUE)
saveRDS(toSave, paste0(outdatadir, "DESeq2_rez_simple.RDS"))
significant <- res_dt %>% 
  .[padj <= pval, ] %>% 
  .[abs(log2FoldChange) >= lfc, ]
vsd <- vst(dds, blind=FALSE)
getCorHeatmap(assay(vsd))
makePCA(vsd)
ggarrange(getHeatMapDEG(assay(vsd), significant))
getVolcano(res_dt, pval, lfc)
```

